// Code generated by "internal/cmd/i18n"; DO NOT EDIT.

package i18n

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
)
// initEnUS will init en_US support.
func initEnUS(tag language.Tag) {
	_ = message.SetString(tag, "auth source not exist", "auth source not exist")
	_ = message.SetString(tag, "auth source not exists or not enabled", "auth source not exists or not enabled")
	_ = message.SetString(tag, "current environment data is abnormal, please contact the administrator", "current environment data is abnormal, please contact the administrator")
	_ = message.SetString(tag, "empty code", "empty code")
	_ = message.SetString(tag, "exchange oauth2 token failed", "exchange oauth2 token failed")
	_ = message.SetString(tag, "failed to connect ldap server", "failed to connect ldap server")
	_ = message.SetString(tag, "failed to connect ldap server with tls", "failed to connect ldap server with tls")
	_ = message.SetString(tag, "failed to get auth source", "failed to get auth source")
	_ = message.SetString(tag, "failed to get userinfo from ldap", "failed to get userinfo from ldap")
	_ = message.SetString(tag, "failed to get userinfo from ldap, more than one result", "failed to get userinfo from ldap, more than one result")
	_ = message.SetString(tag, "failed to get userinfo from oauth provider", "failed to get userinfo from oauth provider")
	_ = message.SetString(tag, "failed to get username from oauth provider", "failed to get username from oauth provider")
	_ = message.SetString(tag, "invalid credential", "invalid credential")
	_ = message.SetString(tag, "login source not provide", "login source not provide")
	_ = message.SetString(tag, "message type %s is invalid", "message type %s is invalid")
	_ = message.SetString(tag, "please login first", "please login first")
	_ = message.SetString(tag, "source not exist", "source not exist")
	_ = message.SetString(tag, "source not match", "source not match")
	_ = message.SetString(tag, "state not provide", "state not provide")
	_ = message.SetString(tag, "system error", "system error")
	_ = message.SetString(tag, "you have no permission to do this operation", "you have no permission to do this operation")
	_ = message.SetString(tag, "you have no permission to do this operation, you must be an admin in any virtual space firstly", "you have no permission to do this operation, you must be an admin in any virtual space firstly")
	_ = message.SetString(tag, "you have no permission to operate the environment %s", "you have no permission to operate the environment %s")
	_ = message.SetString(tag, "you have no permission to operate the project %s", "you have no permission to operate the project %s")
	_ = message.SetString(tag, "you have no permission to operate the tenant %s", "you have no permission to operate the tenant %s")
	_ = message.SetString(tag, "you have no permission to operate the virtual space %s", "you have no permission to operate the virtual space %s")
}
// initZhCN will init zh_CN support.
func initZhCN(tag language.Tag) {
	_ = message.SetString(tag, "auth source not exist", "身份验证源不存在")
	_ = message.SetString(tag, "auth source not exists or not enabled", "身份验证源不存在或未启用")
	_ = message.SetString(tag, "current environment data is abnormal, please contact the administrator", "当前环境数据异常，请联系管理员")
	_ = message.SetString(tag, "empty code", "空代码")
	_ = message.SetString(tag, "exchange oauth2 token failed", "exchange oauth2 token 失败")
	_ = message.SetString(tag, "failed to connect ldap server", "连接ldap 服务器失败")
	_ = message.SetString(tag, "failed to connect ldap server with tls", "连接ldap服务器与tls失败")
	_ = message.SetString(tag, "failed to get auth source", "未能获取身份验证源")
	_ = message.SetString(tag, "failed to get userinfo from ldap", "从 ldap 获取用户信息失败")
	_ = message.SetString(tag, "failed to get userinfo from ldap, more than one result", "从 ldap获取用户信息失败，多个结果")
	_ = message.SetString(tag, "failed to get userinfo from oauth provider", "从 oauth 提供商获取用户信息失败")
	_ = message.SetString(tag, "failed to get username from oauth provider", "从 oauth 提供商获取用户名失败")
	_ = message.SetString(tag, "invalid credential", "凭证无效")
	_ = message.SetString(tag, "login source not provide", "登录源未提供")
	_ = message.SetString(tag, "message type %s is invalid", "消息类型 %s 无效")
	_ = message.SetString(tag, "please login first", "请先登录")
	_ = message.SetString(tag, "source not exist", "源不存在")
	_ = message.SetString(tag, "source not match", "源不匹配")
	_ = message.SetString(tag, "state not provide", "状态未提供")
	_ = message.SetString(tag, "system error", "系统错误")
	_ = message.SetString(tag, "you have no permission to do this operation", "您没有进行此操作的权限")
	_ = message.SetString(tag, "you have no permission to do this operation, you must be an admin in any virtual space firstly", "您没有进行此操作的权限，您必须首先是任何虚拟空间的管理员")
	_ = message.SetString(tag, "you have no permission to operate the environment %s", "您没有权限操作环境 %s")
	_ = message.SetString(tag, "you have no permission to operate the project %s", "您没有权限操作项目 %s")
	_ = message.SetString(tag, "you have no permission to operate the tenant %s", "您无权操作租户 %s")
	_ = message.SetString(tag, "you have no permission to operate the virtual space %s", "您没有权限操作虚拟空间 %s")
}

