apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "kubegems.installer.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: installer
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.installer.replicaCount }}
  {{- if .Values.installer.updateStrategy }}
  strategy: {{- toYaml .Values.installer.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: installer
  template:
    metadata:
      {{- if .Values.installer.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.installer.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: installer
        {{- if .Values.installer.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.installer.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "kubegems.installer.serviceAccountName" . }}
      {{- include "kubegems.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.installer.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.installer.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.installer.enableAffinity -}}
      {{- if .Values.installer.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.installer.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.installer.podAffinityPreset "component" "installer" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.installer.podAntiAffinityPreset "component" "installer" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.installer.nodeAffinityPreset.type "key" .Values.installer.nodeAffinityPreset.key "values" .Values.installer.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- end }}
      {{- if .Values.installer.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.installer.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.installer.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.installer.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.installer.priorityClassName }}
      priorityClassName: {{ .Values.installer.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.installer.schedulerName }}
      schedulerName: {{ .Values.installer.schedulerName | quote }}
      {{- end }}
      {{- if .Values.installer.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.installer.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: installer
          image: {{ include "kubegems.installer.image" . }}
          imagePullPolicy: {{ .Values.installer.image.pullPolicy }}
          {{- if .Values.installer.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.installer.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.installer.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.installer.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.installer.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.installer.args "context" $) | nindent 12 }}
          {{- else }}
          args:
            - installer
            - --chartsdir=/app/charts
            - --pluginsdir=/app/plugins
            {{- if .Values.installer.leaderElection.enabled }}
            - --enableleaderelection
            {{- end }}
            - --probeaddr=:{{- .Values.installer.containerPorts.probe }}
            {{- if .Values.installer.metrics.enabled }}
            - --metricsaddr=:{{- .Values.installer.metrics.service.port }}
            {{- end }}
            {{- if .Values.installer.extraArgs }}
            {{- include "common.tplvalues.render" (dict "value" .Values.installer.extraArgs "context" $) | nindent 12 }}
            {{- end }}
          {{- end }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.installer.logLevel }}
            {{- if .Values.installer.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.installer.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if or .Values.installer.extraEnvVarsCM .Values.installer.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.installer.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.installer.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.installer.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.installer.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- end }}
          {{- if .Values.installer.resources }}
          resources: {{- toYaml .Values.installer.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: probe
              containerPort: {{ .Values.installer.containerPorts.probe }}
              protocol: TCP
            {{- if .Values.installer.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.installer.metrics.service.port }}
              protocol: TCP
            {{- end }}
          {{- if .Values.installer.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.installer.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /healthz
              port: probe
          {{- else if .Values.installer.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.installer.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.installer.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.installer.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /healthz
              port: probe
          {{- else if .Values.installer.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.installer.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.installer.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.installer.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /healthz
              port: http
          {{- else if .Values.installer.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.installer.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.installer.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.installer.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.installer.extraVolumeMounts }}
          volumeMounts: {{- include "common.tplvalues.render" (dict "value" .Values.installer.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.installer.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.installer.sidecars "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.installer.extraVolumes }}
        volumes: {{- include "common.tplvalues.render" (dict "value" .Values.installer.extraVolumes "context" $) | nindent 8 }}
        {{- end }}