{{- if eq .Values.plugins.role "core" -}}
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: mysql
spec:
  kind: helm
  installNamespace: kubegems
  repo: https://charts.bitnami.com/bitnami
  enabled: true
---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: kubegems
spec:
  kind: helm
  enabled: true
  installNamespace: kubegems
  values:
    mysql:
      enabled: false
    externalDatabase:
      enabled: true
{{- end -}}