{{- if eq .Values.plugins.role "local" -}}
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: argo-rollouts
spec:
  kind: helm
  installNamespace: argo-rollouts
  enabled: true
---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: cert-manager
spec:
  kind: helm
  enabled: true
  installNamespace: cert-manager
  values:
    installCRDs: true
---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: jaeger
spec:
  kind: helm
  installNamespace: observability
  enabled: true
---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: loki-stack
spec:
  kind: helm
  installNamespace: loki-stack
  enabled: true
---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: metrics-server
spec:
  kind: helm
  installNamespace: kube-system
  enabled: true
---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: kube-prometheus-stack
spec:
  kind: helm
  installNamespace: prometheus
  enabled: true
---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: gateway
spec:
  kind: native
  installNamespace: kubegems-gateway
  enabled: true
---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: kubegems-local
spec:
  kind: helm
  installNamespace: kubegems-local
  enabled: true
  values:
    agent:
      image:
        tag: {{ .Values.plugins.values.kubegemsVersion | quote }}
    controller:
      image:
        tag: {{ .Values.plugins.values.kubegemsVersion | quote }}
{{- end -}}