apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: controller
  newName: harbor.cloudminds.com/gemscloud/gems-controller
  newTag: v0.3.5-3-g2af124d-dirty
kind: Kustomization
resources:
- manager.yaml
