# syntax=docker/dockerfile:1
# Ref: https://www.docker.com/blog/how-to-rapidly-build-multi-architecture-images-with-buildx/
FROM --platform=${BUILDPLATFORM} kubegems/kubectl:latest
ARG TARGETOS TARGETARCH
COPY kubegems-edge-agent-${TARGETOS}-${TARGETARCH} /app/edge-agent
WORKDIR /app
ENTRYPOINT ["/app/edge-agent"]