FROM alpine
RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories 
RUN apk update && apk add tini bash bash-completion kubectl curl
RUN mv /etc/profile.d/color_prompt.sh.disabled /etc/profile.d/color_prompt.sh
ENTRYPOINT ["/sbin/tini", "--"]
CMD [ "sleep","infinity" ]