apiVersion: kubegems.io/v1beta1
kind: TenantGateway
metadata:
  name: mytg
  # labels:
  #   kubegems.io/tenant: gems-1
spec:
  # replicas: 1
  tenant: t-gems-a
  # ingressClass: mytg-slt
  type: NodePort
  # service:
  #   extraLabels:
  #     wo: henshuai
  # workload:
  #   extraLabels:
  #     tenant: gems-1
  #     www: aaa
  #   resources:
  #     limits:
  #       cpu: 200m
  #       memory: 50Mi
  #     requests:
  #       cpu: 100m
  #       memory: 10Mi
  configMapData:
    worker-processes: "4"
  #   client-max-body-size: 20M
  #   worker-connections: "1111"
  #   http2: "True"
