# https://github.com/rancher/local-path-provisioner/tree/master/deploy/chart
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  kind: helm
  url: https://github.com/rancher/local-path-provisioner/archive/refs/tags/v0.0.22.tar.gz
  path: local-path-provisioner-0.0.22/deploy/chart/local-path-provisioner
  version: 0.0.22
  values:
    storageClass:
      defaultClass: true
      provisionerName: rancher.io/local-path
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /data
    image:
      # repository: rancher/local-path-provisioner
      repository: registry.cn-beijing.aliyuncs.com/kubegems/local-path-provisioner
      tag: v0.0.22
      pullPolicy: IfNotPresent
    helperImage:
      repository: registry.cn-beijing.aliyuncs.com/kubegems/busybox
    configmap:
      # specify the config map name
      name: local-path-config
      # specify the custom script for setup and teardown
      setup: |-
        #!/bin/sh
        set -eu
        mkdir -m 0777 -p "$VOL_DIR"
      teardown: |-
        #!/bin/sh
        set -eu
        rm -rf "$VOL_DIR"
      # specify the custom helper pod yaml
      helperPod: |-
        apiVersion: v1
        kind: Pod
        metadata:
          name: helper-pod
        spec:
          containers:
          - name: helper-pod
            image: registry.cn-beijing.aliyuncs.com/kubegems/busybox:latest
            imagePullPolicy: IfNotPresent
