apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: kubegems
  namespace: kubegems
spec:
  enabled: true
  kind: helm
  repo: https://charts.kubegems.io/kubegems
  installNamespace: kubegems
  values:
    global:
      imageRegistry: registry.cn-beijing.aliyuncs.com
    ingress:
      hostname: dashboard.kubegems.io # change me to use a production hostname
    gitea:
      persistence:
        storageClass: local-path # change me to use a production storage class
      image:
        repository: registry.cn-beijing.aliyuncs.com/kubegems/gitea
    mysql:
      image:
        repository: kubegems/mysql
    redis:
      image:
        repository: kubegems/redis
    chartmuseum:
      image:
        repository: kuebgems/chartmuseum
      persistence:
        enabled: true
        sieze: 5Gi
    ingress:
      hostname: dashboard.kubegems.io
