apiVersion: plugins.kubegems.io/v1beta1
kind: Installer
metadata:
  name: kubegems-local
  namespace: kubegems-installer
spec:
  plugins:
    - name: cert-manager
      namespace: cert-manager
      enabled: true
      values:
        installCRDs: true
    - name: argo-rollouts
      namespace: argo-rollouts
    - name: jaeger
      namespace: observability
    - name: loki-stack
      namespace: loki-stack
    - name: metrics-server
      namespace: kube-system
    - name: kube-prometheus-stack
      namespace: prometheus
      enabled: true
    - name: gateway
      namespace: kubegems-gateway
      kind: native
      enabled: true
    - name: kubegems-local
      namespace: kubegems-local
      enabled: true
