apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: kubegems
  namespace: kubegems
spec:
  enabled: true
  kind: helm
  repo: https://charts.kubegems.io/kubegems
  installNamespace: kubegems
  values:
    global:
      imageRegistry: registry.cn-beijing.aliyuncs.com
      kubegemsVersion: main
      storageClass: local-path # change me to use a production storage class
    mysql:
      image:
        repository: kubegems/mysql
        persistence:
          enabled: true
          size: 20Gi
    redis:
      image:
        repository: kubegems/redis
      master:
        persistence:
          enabled: true
          size: 5Gi
      volumePermissions:
        enabled: true
        image:
          repository: kubegems/bitnami-shell
    argo-cd:
      image:
        repository: kubegems/argo-cd
      redis:
        image:
          repository: kubegems/redis
    gitea:
      image:
        repository: kubegems/gitea
      persistence:
        enabled: true
        size: 10Gi 
    chartmuseum:
      image:
        repository: kubegems/chartmuseum
      persistence:
        enabled: true
        sieze: 5Gi
    ingress:
      hostname: dashboard.kubegems.io
