apiVersion: v1
kind: Namespace
metadata:
  name: kubegems
---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: mysql
  namespace: kubegems
spec:
  kind: helm
  installNamespace: kubegems
  repo: https://charts.bitnami.com/bitnami
  enabled: true
---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: kubegems
  namespace: kubegems
spec:
  kind: helm
  enabled: true
  installNamespace: kubegems
  values:
    api:
      image:
        repository: cnfatal/kubegems
        pullPolicy: Always
    init:
      image:
        repository: cnfatal/kubegems
        pullPolicy: Always
      charts:
        image:
          repository: cnfatal/charts-uploader
          pullPolicy: Always
    ingress:
      hostname: dashboard.k8s.fatalc.cn
    mysql:
      enabled: false
    externalDatabase:
      enabled: true
