bases:
  - ../crd
  - ../rbac
  - ../manager
  - ../webhook
  - ../certmanager
namePrefix: gems-
namespace: gemcloud-system
patchesStrategicMerge:
  - manager_auth_proxy_patch.yaml
  - manager_webhook_patch.yaml
  - webhookcainjection_patch.yaml
vars:
- name: CERTIFICATE_NAMESPACE
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1
    name: controller-cert
  fieldref:
    fieldpath: metadata.namespace
- name: CERTIFICATE_NAME
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1
    name: controller-cert
commonLabels:
  app.kubernetes.io/name: gems-controller-manager
  control-plane: controller-manager
