{{- if and .Values.api.jwt.enabled (not .Values.api.jwt.useCertManager) }}
{{- $ca := genCA "kubegems-ca" 365 }}
{{- $cert := genSignedCert (include "kubegems.api.fullname" .) nil (list (printf "%s.%s.svc" (include "kubegems.api.fullname" .) .Release.Namespace) (printf "%s-webhook.%s.svc.%s" (include "kubegems.api.fullname" .) .Release.Namespace .Values.clusterDomain)) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kubegems.api.jwt.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: agent
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}
