//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2022 The kubegems.io Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Certs) DeepCopyInto(out *Certs) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Cert != nil {
		in, out := &in.Cert, &out.Cert
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Certs.
func (in *Certs) DeepCopy() *Certs {
	if in == nil {
		return nil
	}
	out := new(Certs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeCluster) DeepCopyInto(out *EdgeCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeCluster.
func (in *EdgeCluster) DeepCopy() *EdgeCluster {
	if in == nil {
		return nil
	}
	out := new(EdgeCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EdgeCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeClusterList) DeepCopyInto(out *EdgeClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EdgeCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeClusterList.
func (in *EdgeClusterList) DeepCopy() *EdgeClusterList {
	if in == nil {
		return nil
	}
	out := new(EdgeClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EdgeClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeClusterSpec) DeepCopyInto(out *EdgeClusterSpec) {
	*out = *in
	in.Register.DeepCopyInto(&out.Register)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeClusterSpec.
func (in *EdgeClusterSpec) DeepCopy() *EdgeClusterSpec {
	if in == nil {
		return nil
	}
	out := new(EdgeClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeClusterStatus) DeepCopyInto(out *EdgeClusterStatus) {
	*out = *in
	in.Register.DeepCopyInto(&out.Register)
	in.Tunnel.DeepCopyInto(&out.Tunnel)
	if in.Manufacture != nil {
		in, out := &in.Manufacture, &out.Manufacture
		*out = make(ManufactureStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeClusterStatus.
func (in *EdgeClusterStatus) DeepCopy() *EdgeClusterStatus {
	if in == nil {
		return nil
	}
	out := new(EdgeClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeHub) DeepCopyInto(out *EdgeHub) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeHub.
func (in *EdgeHub) DeepCopy() *EdgeHub {
	if in == nil {
		return nil
	}
	out := new(EdgeHub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EdgeHub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeHubList) DeepCopyInto(out *EdgeHubList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EdgeHub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeHubList.
func (in *EdgeHubList) DeepCopy() *EdgeHubList {
	if in == nil {
		return nil
	}
	out := new(EdgeHubList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EdgeHubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeHubSpec) DeepCopyInto(out *EdgeHubSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeHubSpec.
func (in *EdgeHubSpec) DeepCopy() *EdgeHubSpec {
	if in == nil {
		return nil
	}
	out := new(EdgeHubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeHubStatus) DeepCopyInto(out *EdgeHubStatus) {
	*out = *in
	in.Tunnel.DeepCopyInto(&out.Tunnel)
	if in.Manufacture != nil {
		in, out := &in.Manufacture, &out.Manufacture
		*out = make(ManufactureStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeHubStatus.
func (in *EdgeHubStatus) DeepCopy() *EdgeHubStatus {
	if in == nil {
		return nil
	}
	out := new(EdgeHubStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ManufactureStatus) DeepCopyInto(out *ManufactureStatus) {
	{
		in := &in
		*out = make(ManufactureStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManufactureStatus.
func (in ManufactureStatus) DeepCopy() ManufactureStatus {
	if in == nil {
		return nil
	}
	out := new(ManufactureStatus)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegisterInfo) DeepCopyInto(out *RegisterInfo) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.Certs != nil {
		in, out := &in.Certs, &out.Certs
		*out = new(Certs)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegisterInfo.
func (in *RegisterInfo) DeepCopy() *RegisterInfo {
	if in == nil {
		return nil
	}
	out := new(RegisterInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegisterStatus) DeepCopyInto(out *RegisterStatus) {
	*out = *in
	if in.LastRegister != nil {
		in, out := &in.LastRegister, &out.LastRegister
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegisterStatus.
func (in *RegisterStatus) DeepCopy() *RegisterStatus {
	if in == nil {
		return nil
	}
	out := new(RegisterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelStatus) DeepCopyInto(out *TunnelStatus) {
	*out = *in
	if in.LastOnlineTimestamp != nil {
		in, out := &in.LastOnlineTimestamp, &out.LastOnlineTimestamp
		*out = (*in).DeepCopy()
	}
	if in.LastOfflineTimestamp != nil {
		in, out := &in.LastOfflineTimestamp, &out.LastOfflineTimestamp
		*out = (*in).DeepCopy()
	}
	if in.LastHeartBeatTimestamp != nil {
		in, out := &in.LastHeartBeatTimestamp, &out.LastHeartBeatTimestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelStatus.
func (in *TunnelStatus) DeepCopy() *TunnelStatus {
	if in == nil {
		return nil
	}
	out := new(TunnelStatus)
	in.DeepCopyInto(out)
	return out
}
