apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubegems.msgbus.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: msgbus
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.msgbus.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.msgbus.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if and .Values.msgbus.metrics.enabled .Values.msgbus.metrics.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.msgbus.metrics.service.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.msgbus.service.type }}
  {{- if or (eq .Values.msgbus.service.type "LoadBalancer") (eq .Values.msgbus.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.msgbus.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.msgbus.service.type "LoadBalancer") (not (empty .Values.msgbus.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.msgbus.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.msgbus.service.type "LoadBalancer") (not (empty .Values.msgbus.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.msgbus.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.msgbus.service.ports.http }}
      protocol: TCP
      targetPort: http
    {{- if .Values.msgbus.metrics.enabled }}
    - name: metrics
      port: {{ .Values.msgbus.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
      {{- if (and (or (eq .Values.msgbus.service.type "NodePort") (eq .Values.msgbus.service.type "LoadBalancer")) (not (empty .Values.msgbus.service.nodePorts.metrics))) }}
      nodePort: {{ .Values.server.msgbus.nodePorts.metrics }}
      {{- else if eq .Values.msgbus.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- end }}
    {{- if .Values.msgbus.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.msgbus.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: msgbus
