# permissions for end users to view environments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: environment-viewer-role
rules:
  - apiGroups:
      - kubegems.io
    resources:
      - environments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubegems.io
    resources:
      - environments/status
    verbs:
      - get
