# permissions for end users to edit environments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: environment-editor-role
rules:
  - apiGroups:
      - kubegems.io
    resources:
      - environments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kubegems.io
    resources:
      - environments/status
    verbs:
      - get
