//
//Copyright The Kubegems Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: pkg/edge/tunnel/proto/tunnel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src    string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	SrcID  int64  `protobuf:"varint,2,opt,name=srcID,proto3" json:"srcID,omitempty"`
	Dest   string `protobuf:"bytes,3,opt,name=dest,proto3" json:"dest,omitempty"`
	DestID int64  `protobuf:"varint,4,opt,name=destID,proto3" json:"destID,omitempty"`
	Kind   int64  `protobuf:"varint,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Data   []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Error  string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_edge_tunnel_proto_tunnel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_edge_tunnel_proto_tunnel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_pkg_edge_tunnel_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Packet) GetSrcID() int64 {
	if x != nil {
		return x.SrcID
	}
	return 0
}

func (x *Packet) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *Packet) GetDestID() int64 {
	if x != nil {
		return x.DestID
	}
	return 0
}

func (x *Packet) GetKind() int64 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Packet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Packet) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_edge_tunnel_proto_tunnel_proto protoreflect.FileDescriptor

var file_pkg_edge_tunnel_proto_tunnel_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9a, 0x01, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72,
	0x63, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x72, 0x63, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x73, 0x72, 0x63, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x73,
	0x74, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x32, 0x30, 0x0a, 0x0b, 0x50, 0x65, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x21, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x07, 0x2e, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x1a, 0x07, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x2c, 0x5a, 0x2a, 0x6b, 0x75, 0x62, 0x65, 0x67, 0x65, 0x6d, 0x73, 0x2e,
	0x69, 0x6f, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x67, 0x65, 0x6d, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x65, 0x64, 0x67, 0x65, 0x2f, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_edge_tunnel_proto_tunnel_proto_rawDescOnce sync.Once
	file_pkg_edge_tunnel_proto_tunnel_proto_rawDescData = file_pkg_edge_tunnel_proto_tunnel_proto_rawDesc
)

func file_pkg_edge_tunnel_proto_tunnel_proto_rawDescGZIP() []byte {
	file_pkg_edge_tunnel_proto_tunnel_proto_rawDescOnce.Do(func() {
		file_pkg_edge_tunnel_proto_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_edge_tunnel_proto_tunnel_proto_rawDescData)
	})
	return file_pkg_edge_tunnel_proto_tunnel_proto_rawDescData
}

var file_pkg_edge_tunnel_proto_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_edge_tunnel_proto_tunnel_proto_goTypes = []interface{}{
	(*Packet)(nil), // 0: Packet
}
var file_pkg_edge_tunnel_proto_tunnel_proto_depIdxs = []int32{
	0, // 0: PeerService.Connect:input_type -> Packet
	0, // 1: PeerService.Connect:output_type -> Packet
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_edge_tunnel_proto_tunnel_proto_init() }
func file_pkg_edge_tunnel_proto_tunnel_proto_init() {
	if File_pkg_edge_tunnel_proto_tunnel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_edge_tunnel_proto_tunnel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_edge_tunnel_proto_tunnel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_edge_tunnel_proto_tunnel_proto_goTypes,
		DependencyIndexes: file_pkg_edge_tunnel_proto_tunnel_proto_depIdxs,
		MessageInfos:      file_pkg_edge_tunnel_proto_tunnel_proto_msgTypes,
	}.Build()
	File_pkg_edge_tunnel_proto_tunnel_proto = out.File
	file_pkg_edge_tunnel_proto_tunnel_proto_rawDesc = nil
	file_pkg_edge_tunnel_proto_tunnel_proto_goTypes = nil
	file_pkg_edge_tunnel_proto_tunnel_proto_depIdxs = nil
}
