{
 "title": "物理机基础指标（全局）",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_exporter_build_info, instance)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(node_exporter_build_info{instance=\"$node\"}, host)"
    }
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 0 },
   "options": {
    "content": "<div class=\"left dashboard-header\">\n   <span>服务器基本信息</span>\n</div>"
   }
  },
  {
   "title": "主机容器内存TOP 10",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, container_memory_rss{node=~\"$host\",pod!=\"\",container!=\"\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node\"}",
     "legendFormat": "系统运行时间"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU使用率"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "内存使用率"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{instance=~\"$node\"}",
     "legendFormat": "Sockets"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_processes_max_processes{instance=\"$node\"}",
     "legendFormat": "Max Processes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))",
     "legendFormat": "Cores"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100",
     "legendFormat": "CPU IOwait"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"} / node_filefd_maximum{instance=~\"$node\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_processes_max_threads {instance=\"$node\"}",
     "legendFormat": "Max Threads"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_vmstat_oom_kill{instance=\"$node\"}",
     "legendFormat": "OOM Kill"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 9, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 6 },
   "options": {
    "content": "<div class=\"left dashboard-header\">\n    <span>系统状态</span>\n</div>"
   }
  },
  {
   "title": "分区空闲率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$node\",fstype=~\"ext4|xfs\",mountpoint!~\"/var/lib/(heketi|kubelet).*\",mountpoint!~\"/run.*\"} / node_filesystem_size_bytes{instance=~\"$node\",fstype=~\"ext4|xfs\",mountpoint!~\"/var/lib/(heketi|kubelet).*\",mountpoint!~\"/run.*\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "系统负载",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "Load 1"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "Load 5"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "Load 15"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m])) * 100)",
     "legendFormat": "us"
    },
    {
     "expr": "(avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m])) * 100)",
     "legendFormat": "system"
    },
    {
     "expr": "(avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1m])) * 100)",
     "legendFormat": "iowat"
    },
    {
     "expr": "(avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"irq\"}[1m])) * 100)",
     "legendFormat": "irq"
    },
    {
     "expr": "(avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"softirq\"}[1m])) * 100)",
     "legendFormat": "softirq"
    },
    {
     "expr": "(avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"steal\"}[1m])) * 100)",
     "legendFormat": "steal"
    },
    {
     "expr": "(avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"nice\"}[1m])) * 100)",
     "legendFormat": "nice"
    }
   ]
  },
  {
   "title": "内存分配状态",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$node\",id=\"/kubepods\"})",
     "legendFormat": "容器空间"
    },
    {
     "expr": "sum(container_memory_rss{instance=\"$node\",id=\"/system.slice\",pod_name=\"\"}) or sum(container_memory_rss{instance=\"$node\",id=~\"/system.slice/.*.service\"})",
     "legendFormat": "系统空间"
    },
    {
     "expr": "sum(container_memory_rss{instance=\"$node\",id=\"/user.slice\"}) or sum(container_memory_rss{instance=\"$node\",id=~\"/user.slice/.*\"})",
     "legendFormat": "用户空间"
    }
   ]
  },
  {
   "title": "CPU 上下文切换和中断",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=\"$node\"}[5m])",
     "legendFormat": "上下文切换"
    },
    {
     "expr": "irate(node_intr_total{instance=~\"$node\"}[5m])",
     "legendFormat": "CPU中断"
    }
   ]
  },
  {
   "title": "内存使用状态",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"$node\"} - node_memory_Cached_bytes{instance=~\"$node\"} - node_memory_Buffers_bytes{instance=~\"$node\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "剩余磁盘文件数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_filesystem_files_free{instance=~\"$node\",fstype=~\"ext4|xfs\",mountpoint!~\"/var/lib/[heketi/kubelet].*\",mountpoint!~\"/run.*\"} / node_filesystem_files{instance=~\"$node\",fstype=~\"ext4|xfs\",mountpoint!~\"/var/lib/[heketi/kubelet].*\",mountpoint!~\"/run.*\"} ",
     "legendFormat": "persent"
    }
   ]
  },
  {
   "title": "OOM Killer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_vmstat_oom_kill{instance=~'$node'} - node_vmstat_oom_kill{instance=~'$node'} offset 1m",
     "legendFormat": "oom kill"
    }
   ]
  },
  {
   "title": "磁盘ReadOnly",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 20 },
   "targets": [
    {
     "expr": "sum(node_filesystem_readonly{instance=~\"$node\",fstype=~\"ext4|xfs\",mountpoint!~\"/var/lib/(kubelet|heketi)/.*\"})  by (mountpoint)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "<div class=\"left dashboard-header\">\n   <span>进(线)程状态</span>\n</div>"
   }
  },
  {
   "title": "进程状态",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    {
     "expr": "node_processes_state{instance=\"$node\"}",
     "legendFormat": "State:{{state}}"
    }
   ]
  },
  {
   "title": "进程/线程数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_processes_pids{instance=\"$node\"}",
     "legendFormat": "进程数"
    },
    {
     "expr": "node_processes_threads{instance=\"$node\"}",
     "legendFormat": "线程数"
    }
   ]
  },
  {
   "title": "进程状态",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    {
     "expr": "node_procs_blocked{instance=~\"$node\"}",
     "legendFormat": "等待I/O的进程"
    },
    {
     "expr": "node_procs_running{instance=~\"$node\"}",
     "legendFormat": "可运行的进程"
    },
    {
     "expr": "rate(node_forks_total{instance=\"$node\"}[5m])",
     "legendFormat": "进程fork数"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 },
   "options": {
    "content": "<div class=\"left dashboard-header\">\n   <span>网络流量和连接状态</span>\n</div>"
   }
  },
  {
   "title": "TCP连接状态",
   "type": "graph",
   "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=\"$node\",state!~\".*bytes\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "链路跟踪表",
   "type": "graph",
   "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=\"$node\"}",
     "legendFormat": "active"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{instance=\"$node\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "IPVS连接数",
   "type": "graph",
   "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(node_ipvs_connections_total{instance='$node'}[1m])",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "IPVS连接状态",
   "type": "graph",
   "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_ipvs_backend_connections_active{instance=\"$node\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(node_ipvs_backend_connections_inactive{instance=\"$node\"})",
     "legendFormat": "inactive"
    }
   ]
  },
  {
   "title": "IPVS流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_ipvs_incoming_bytes_total {instance=\"$node\"}[1m])",
     "legendFormat": "下行流量"
    },
    {
     "expr": "irate(node_ipvs_outgoing_bytes_total {instance=\"$node\"}[1m])",
     "legendFormat": "上行流量"
    }
   ]
  },
  {
   "title": "IPVS网络包",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 42 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_ipvs_incoming_packets_total {instance=\"$node\"}[1m])",
     "legendFormat": "下行网络包"
    },
    {
     "expr": "irate(node_ipvs_outgoing_packets_total {instance=\"$node\"}[1m])",
     "legendFormat": "上行网络包"
    }
   ]
  },
  {
   "title": "网卡下行流量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps", "label": "出口（-）/入口（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",device!~\"lo|vnet.*|enp.*\"}[5m])",
     "legendFormat": "{{device}}下行流量"
    }
   ]
  },
  {
   "title": "网卡上行流量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "Bps", "label": "出口（-）/入口（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",device!~\"lo|vnet.*|enp.*\"}[5m])",
     "legendFormat": "{{device}}上行流量"
    }
   ]
  },
  {
   "title": "网卡下行网络包",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "pps", "label": "出口（-）/入口（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=\"$node\",device!~\"lo|vnet.*|enp.*\"}[5m])",
     "legendFormat": "{{device}}下行网络包"
    }
   ]
  },
  {
   "title": "网卡上行网络包",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 48 },
   "yaxes": [
    { "format": "pps", "label": "出口（-）/入口（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{instance=\"$node\",device!~\"lo|vnet.*|enp.*\"}[5m])",
     "legendFormat": "{{device}}上行网络包"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 55 },
   "options": {
    "content": "<div class=\"left dashboard-header\">\n   <span>磁盘状态</span>\n</div>"
   }
  },
  {
   "title": "磁盘读取速率",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",device=~\"[a-z]d[a-z]\"}[5m])",
     "legendFormat": "{{device}}读取速率"
    }
   ]
  },
  {
   "title": "磁盘写入速率",
   "type": "timeseries",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",device=~\"[a-z]d[a-z]\"}[1m])",
     "legendFormat": "{{device}}写入速率"
    }
   ]
  },
  {
   "title": "CPU使用率、磁盘每秒的I/O操作耗费时间（%）",
   "type": "graph",
   "description": "node_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的毫秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 57 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m])) by (instance)",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1m])) by (instance)",
     "legendFormat": "Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\",device=~\"[a-z]d[a-z]\"}[1m])",
     "legendFormat": "{{device}}_每秒I/O操作"
    }
   ]
  },
  {
   "title": "磁盘读取耗时",
   "type": "graph",
   "description": "Read time ms 每个磁盘分区读操作花费的秒数\n\nWrite time ms 每个磁盘分区写操作花费的秒数\n\nIO time ms 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted 每个磁盘分区输入/输出操作花费的加权秒数",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\",device=~\"[a-z]d[a-z]\"}[5m])",
     "legendFormat": "{{device}}读取耗时"
    }
   ]
  },
  {
   "title": "磁盘写入耗时",
   "type": "graph",
   "description": "Read time ms 每个磁盘分区读操作花费的秒数\n\nWrite time ms 每个磁盘分区写操作花费的秒数\n\nIO time ms 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted 每个磁盘分区输入/输出操作花费的加权秒数",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 63 },
   "yaxes": [
    { "format": "s", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\",device=~\"[a-z]d[a-z]\"}[5m])",
     "legendFormat": "{{device}}写入耗时"
    }
   ]
  },
  {
   "title": "磁盘IOPS",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 63 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\",device=~\"[a-z]d[a-z]\"}[5m])",
     "legendFormat": "{{device}}读取"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\",device=~\"[a-z]d[a-z]\"}[5m])",
     "legendFormat": "{{device}}写入"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 69 },
   "options": {
    "content": "<div class=\"left dashboard-header\">\n   <span>其它指标</span>\n</div>"
   }
  },
  {
   "title": "CPU 温度状态",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"$node\"})",
     "legendFormat": "CPU平均温度"
    },
    {
     "expr": "avg(node_hwmon_temp_max_celsius{instance=\"$node\"})",
     "legendFormat": "CPU温度警戒线"
    }
   ]
  }
 ]
}