apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubegems-local.agent.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: agent
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.agent.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.agent.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if and .Values.agent.metrics.enabled .Values.agent.metrics.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.agent.metrics.service.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.agent.service.type }}
  {{- if or (eq .Values.agent.service.type "LoadBalancer") (eq .Values.agent.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.agent.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.agent.service.type "LoadBalancer") (not (empty .Values.agent.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.agent.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.agent.service.type "LoadBalancer") (not (empty .Values.agent.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.agent.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.agent.service.ports.http }}
      protocol: TCP
      targetPort: http
    {{- if .Values.agent.metrics.enabled }}
    - name: metrics
      port: {{ .Values.agent.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
      {{- if (and (or (eq .Values.agent.service.type "NodePort") (eq .Values.agent.service.type "LoadBalancer")) (not (empty .Values.agent.service.nodePorts.metrics))) }}
      nodePort: {{ .Values.server.agent.nodePorts.metrics }}
      {{- else if eq .Values.agent.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- end }}
    {{- if .Values.agent.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.agent.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
